# Generated by Django 3.0.4 on 2020-03-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20200328_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default=12345678901, max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
