# Generated by Django 3.0.4 on 2020-03-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_auto_20200328_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregado',
            name='departamentos',
            field=models.ManyToManyField(blank=True, to='clientes.Departamento'),
        ),
    ]
